# Site settings
title: T-Eco-Evo
email: gokhale@evolbio.mpg.de
url: #https://example.github.io
description: "Research Group- Theoretical Eco-evolutionary Dynamics, Department of Evolutionary Theory,\n Max Planck Institute for Evolutionary Biology."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: T-eco-evo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/GokhaleCS
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
